apiVersion: v1
kind: Service
metadata:
  name: my-nginx1-service
spec:
  selector:
    app:  my-nginx1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 31111